# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171003_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
