# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20171003_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='featured_img',
            field=models.FileField(null=True, upload_to='uploads/item'),
        ),
    ]
