# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20171019_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='base.Item'),
        ),
    ]
