# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20171022_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
