# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20171023_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='base.Tag'),
        ),
    ]
