# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20171023_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='audioanno',
            old_name='annotation_id',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='audioanno',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='imageanno',
            old_name='annotation_id',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='imageanno',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='itemedit',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itemedit',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='itemfollow',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itemfollow',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='reported',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='reported',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taglist',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='taglist',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='textanno',
            old_name='annotation_id',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='textanno',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='userratedannotation',
            old_name='annotation_id',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='userratedannotation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userratedcomment',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='userratedcomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userrateditem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='userrateditem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='videoanno',
            old_name='annotation_id',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='videoanno',
            old_name='media_id',
            new_name='media',
        ),
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
