# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20171114_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
