# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20171121_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='endDate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='startDate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
