# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20171204_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioanno',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='audioanno',
            name='media',
        ),
        migrations.RemoveField(
            model_name='imageanno',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='imageanno',
            name='media',
        ),
        migrations.RemoveField(
            model_name='textanno',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='textanno',
            name='media',
        ),
        migrations.RemoveField(
            model_name='videoanno',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='videoanno',
            name='media',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='rate',
            new_name='h',
        ),
        migrations.AddField(
            model_name='annotation',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotated_media', to='base.Media'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AudioAnno',
        ),
        migrations.DeleteModel(
            name='ImageAnno',
        ),
        migrations.DeleteModel(
            name='TextAnno',
        ),
        migrations.DeleteModel(
            name='VideoAnno',
        ),
    ]
