# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_reported_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reported',
            new_name='Report',
        ),
    ]
